CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `open_id` varchar(64) DEFAULT NULL COMMENT '微信openId',
  `user_name` varchar(32) DEFAULT NULL COMMENT '用户名称',
  `sex` varchar(16) DEFAULT NULL COMMENT '性别:FEMALE(女),MALE(男)',
  `phone` varchar(32) NOT NULL COMMENT '联系方式',
  `birthday` varchar(16) DEFAULT NULL COMMENT '生日',
  `member_no` varchar(64) DEFAULT NULL COMMENT '会员号',
  `member_face_no` varchar(64) DEFAULT NULL COMMENT '会员面卡号',
  `member_type` varchar(32) DEFAULT 'RECHARGE' COMMENT 'RECHARGE(充值会员),INTEGRAL(积分会员),SUPER(超级会员)',
  `bar_code_url` varchar(255) DEFAULT NULL COMMENT '会员条形码',
  `face_img` varchar(255) DEFAULT NULL COMMENT '人脸图片url',
  `province` varchar(50) DEFAULT NULL COMMENT '省份',
  `city` varchar(50) DEFAULT NULL COMMENT '城市',
  `district` varchar(50) DEFAULT NULL COMMENT '地区',
  `address` varchar(128) DEFAULT NULL COMMENT '详细地址',
  `channel` varchar(32) DEFAULT NULL COMMENT '会员来源，深圳万科：SZ_VANKE',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_reset_pwd` varchar(16) DEFAULT NULL COMMENT '是否重置密码UNRESETPWD("待修改"),RESETPWD("已修改")',
  `member_category` varchar(50) DEFAULT 'GENERAL' COMMENT '会员类别：‘GENERAL'':普通，‘OWNER’住这儿业主认证会员',
  `shop_code` varchar(16) DEFAULT NULL,
  `union_id` varchar(64) DEFAULT NULL,
  `area` varchar(32) DEFAULT NULL,
  `status` int(1) DEFAULT '1' COMMENT '启用：1，禁用：0',
  `password` varchar(255) DEFAULT NULL COMMENT '密码',
  `salt` varchar(50) DEFAULT NULL COMMENT '密码盐',
  `platform` varchar(32) DEFAULT 'WECHAT',
  `vip_electronic_no` varchar(45) DEFAULT NULL,
  `shop_time` timestamp NULL DEFAULT NULL COMMENT '首单时间',
  `locus` varchar(32) DEFAULT 'STORE' COMMENT 'STORE：门店，MALL：商城',
  `portrait` varchar(1000) DEFAULT NULL COMMENT '头像地址',
  PRIMARY KEY (`id`),
  UNIQUE KEY `phone_unique` (`open_id`,`phone`,`member_no`),
  KEY `member_no_idx` (`member_no`),
  KEY `phone` (`phone`)
) ENGINE=InnoDB AUTO_INCREMENT=88663 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户表';




CREATE TABLE `order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增',
  `member_no` varchar(64) DEFAULT NULL COMMENT '会员编码',
  `order_no` varchar(64) NOT NULL COMMENT '订单号',
  `order_type` varchar(32) NOT NULL COMMENT '订单类型：DELIVERY（配送订单）、SELF_DELIVERY（自提）',
  `org_code` varchar(64) NOT NULL COMMENT '组织编码',
  `sub_order_no` varchar(64) DEFAULT NULL COMMENT '子订单号',
  `total_amount` decimal(19,2) NOT NULL COMMENT '总金额',
  `actual_amount` decimal(19,2) NOT NULL COMMENT '实际金额',
  `share_equally_amount` decimal(19,2) DEFAULT NULL COMMENT '均摊价',
  `transaction_id` varchar(64) DEFAULT NULL COMMENT '交易ID',
  `order_time` timestamp NULL DEFAULT NULL COMMENT '下单时间',
  `pay_time` timestamp NULL DEFAULT NULL COMMENT '付款时间',
  `invalid_time` timestamp NULL DEFAULT NULL COMMENT '失效时间',
  `canceled_reason` varchar(256) DEFAULT NULL COMMENT '取消原因',
  `failed_reason` varchar(256) DEFAULT NULL COMMENT '失败原因',
  `channel` varchar(64) DEFAULT NULL COMMENT '渠道：预售（ADVANC_SALE）',
  `payment_method` varchar(32) DEFAULT NULL COMMENT '付款方式：WECHAT（微信）',
  `delivery_status` varchar(32) DEFAULT NULL COMMENT '配送状态：DELIVERY(待配送)，DELIVERYED(已配送),DELIVERYING(配送中)',
  `status` varchar(32) NOT NULL COMMENT '订单状态:WAIT(待支付),REFUND(退款),PAYED(已支付),FAILED(支付失败),CANCELED(已取消),INVALID(已失效)',
  `remark` varchar(256) DEFAULT NULL COMMENT '备注',
  `ext1` varchar(1024) DEFAULT NULL COMMENT '备用字段1',
  `ext2` varchar(1024) DEFAULT NULL COMMENT '备用字段2',
  `ext3` varchar(1024) DEFAULT NULL COMMENT '备用字段3',
  `ext4` varchar(1024) DEFAULT NULL COMMENT '备用字段4',
  `ext5` varchar(1024) DEFAULT NULL COMMENT '优惠券优惠金额',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建者',
  `operator` varchar(64) DEFAULT NULL COMMENT '修改者',
  `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifed_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `sync_status` varchar(128) DEFAULT 'WAIT' COMMENT '成功（SUCCESS）、失败（FAILED）、待同步（WAIT）',
  `open_id` varchar(128) DEFAULT NULL COMMENT '会员相对公众号唯一标识',
  `invoice_url` varchar(1024) DEFAULT NULL COMMENT '发票地址',
  `invoice_status` varchar(64) DEFAULT NULL COMMENT '发票是否使用，USED(已使用)，UNUSED(未使用)',
  `invoice_used_time` timestamp NULL DEFAULT NULL COMMENT '发票开票时间',
  `sync_status_time` timestamp NULL DEFAULT NULL COMMENT '同步状态时间',
  `delivery_time` timestamp NULL DEFAULT NULL COMMENT '待配送时间',
  `deliverying_time` timestamp NULL DEFAULT NULL COMMENT '配送中时间',
  `deliveryed_time` timestamp NULL DEFAULT NULL COMMENT '已配送时间',
  `point_status` varchar(64) DEFAULT 'UNGIVE' COMMENT '已赠送（GIVE）、未赠送（UNGIVE）',
  `area` varchar(64) DEFAULT 'SZ' COMMENT '区域',
  `platform` varchar(64) DEFAULT 'WECHAT' COMMENT '微信公众号',
  `sync_count` bigint(20) DEFAULT '0' COMMENT '同步次数 上线，3次',
  `ext6` varchar(1024) DEFAULT NULL COMMENT '备用字段6',
  `ext7` varchar(1024) DEFAULT NULL COMMENT '备用字段7',
  `ext8` varchar(1024) DEFAULT NULL COMMENT '备用字段8',
  `ext9` varchar(1024) DEFAULT NULL COMMENT '备用字段9',
  `ext10` varchar(1024) DEFAULT NULL COMMENT '备用字段10',
  `pick_status` varchar(64) DEFAULT 'WAIT_PICK' COMMENT '拣货状态 PICKED-已拣货 WAIT_PICK-待拣货',
  `picked_time` timestamp NULL DEFAULT NULL COMMENT '拣货时间',
  `property_coupon_status` varchar(64) DEFAULT 'GIVE' COMMENT '物业券是否赠送，GIVE(赠送)、UNGIVE(不赠送)',
  `compensation_price` decimal(10,2) DEFAULT '0.00' COMMENT '补差额',
  `ext11` decimal(10,2) DEFAULT '0.00' COMMENT '订单总额，用作流水推送',
  `ext12` decimal(10,2) DEFAULT '0.00' COMMENT '订单实际支付金额，用作流水推送',
  `ext13` decimal(10,2) DEFAULT '0.00' COMMENT '订单总优惠，用作流水推送',
  `point_multiple` decimal(9,2) DEFAULT '1.00' COMMENT '积分倍数',
  `total_order_freight_fee` decimal(10,2) DEFAULT '0.00' COMMENT '订单总运费',
  `order_source` varchar(64) DEFAULT 'COMMON' COMMENT '订单来源 COMMON-普通  GROUPON-团购',
  `first_exclusion` varchar(1) DEFAULT 'Y' COMMENT 'Y-需要判断首单 N-不判断首单条件',
  PRIMARY KEY (`id`),
  KEY `idx_org_code` (`org_code`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB AUTO_INCREMENT=26878 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='订单';


CREATE TABLE `goods_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(255) DEFAULT NULL COMMENT '商品名称',
  `code` varchar(64) DEFAULT NULL COMMENT '商品代码',
  `price` decimal(10,2) DEFAULT '0.00' COMMENT '商品单价',
  `actual_price` decimal(10,2) DEFAULT '0.00' COMMENT '商品折后价',
  `quantity` decimal(10,3) DEFAULT '0.000' COMMENT '总数量',
  `frozen_quantity` decimal(10,3) DEFAULT '0.000' COMMENT '冻结数量',
  `sold_quantity` decimal(10,3) DEFAULT '0.000' COMMENT '已售数量',
  `sorlie_img` varchar(255) DEFAULT NULL COMMENT '缩略图',
  `attribute_img` varchar(255) DEFAULT NULL COMMENT '规格图片',
  `detail_img` varchar(255) DEFAULT NULL COMMENT '详情页图片',
  `goods_type` varchar(32) DEFAULT 'RECOMMEND' COMMENT '商品类型:BANNER(轮播),SELECTION(严选),RECOMMEND(推荐)',
  `order_num` decimal(10,2) DEFAULT '0.00' COMMENT '商品顺序',
  `unit` varchar(32) DEFAULT NULL COMMENT '单位',
  `parent_id` int(11) DEFAULT NULL COMMENT '父ID',
  `spec` varchar(255) DEFAULT NULL COMMENT '规格',
  `description` text COMMENT '描述',
  `status` varchar(32) DEFAULT 'ACTUAL' COMMENT '正常(ACTUAL),失败(INVALID)',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `plu_id` varchar(32) DEFAULT NULL COMMENT '商品ID',
  `org_code` varchar(32) DEFAULT NULL COMMENT '组织结构编码',
  `safe_cku` decimal(10,3) DEFAULT '0.000' COMMENT '安全库存',
  `goods_auxiliary_is_sale` varchar(32) DEFAULT NULL COMMENT '0-否；1-是',
  `goods_is_active` varchar(32) DEFAULT NULL COMMENT '0-否；1-是',
  `goods_yw_status` varchar(32) DEFAULT NULL COMMENT '0-待批;1-正常;2-预淘汰;3-淘汰',
  `goods_is_onLine` varchar(32) DEFAULT NULL COMMENT '0-下线；1-上线',
  `is_visual` varchar(32) DEFAULT 'UNVISUAL' COMMENT '是否可见，可见（VISUAL）、不可见（UNVISUAL）',
  `publish_time` timestamp NULL DEFAULT NULL COMMENT '发布时间',
  `online_time` timestamp NULL DEFAULT NULL COMMENT '上线时间',
  `amount_sync` tinyint(4) DEFAULT '0' COMMENT '是否同步价格，0表示同步，1表示不同步',
  `sku_sync` tinyint(4) DEFAULT '0' COMMENT '是否同步库存，0表示同步，1表示不同步',
  `tax_rate` decimal(19,2) DEFAULT '0.00' COMMENT '税率',
  `ext1` varchar(1024) DEFAULT NULL COMMENT '备注字段1',
  `ext2` varchar(1024) DEFAULT NULL COMMENT '备注字段2',
  `ext3` varchar(1024) DEFAULT NULL COMMENT '备注字段3',
  `ext4` varchar(1024) DEFAULT NULL COMMENT '备注字段4',
  `ext5` varchar(1024) DEFAULT NULL COMMENT '备注字段5',
  `add_number` decimal(10,2) DEFAULT '1.00' COMMENT '叠加基数',
  `virtual_sold` decimal(10,2) DEFAULT '0.00' COMMENT '虚拟已售',
  `monthly_sales` decimal(10,2) DEFAULT '0.00' COMMENT '月销量',
  `virtual_sales_base` decimal(10,2) DEFAULT '0.00' COMMENT '虚拟销量基数',
  `combination_type` varchar(64) NOT NULL DEFAULT 'SINGLE' COMMENT 'PACKAGE-套餐组合  SINGLE_SKU-单品SKU  MULTI_SKU-多品SKU SINGLE-单品',
  `promotion_status` varchar(32) NOT NULL DEFAULT 'FALSE' COMMENT 'TURE-促销中 FALSE-无促销',
  `promotion_desc` varchar(255) DEFAULT NULL COMMENT '促销描述',
  `original_actual_price` decimal(10,2) DEFAULT NULL COMMENT '促销前原价',
  `price2` decimal(10,2) DEFAULT NULL,
  `limit_number` decimal(10,2) DEFAULT '0.00' COMMENT '限制每单购买上限',
  `weight` decimal(10,2) DEFAULT '0.00' COMMENT '商品重量（单位g）',
  `lock_options` varchar(32) DEFAULT 'UNLOCK' COMMENT 'LOCK：锁住，UNLOCK：解锁',
  `expiry_date` varchar(32) DEFAULT NULL COMMENT '保质期时间（单位：天）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`,`plu_id`,`org_code`),
  KEY `publish_time_index` (`publish_time`),
  KEY `code_plu_id_index` (`plu_id`,`org_code`,`code`),
  KEY `org_code_index` (`org_code`),
  KEY `idx_code` (`code`),
  KEY `idx_plu_id` (`plu_id`)
) ENGINE=InnoDB AUTO_INCREMENT=39257 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='商品表';

